# Generated by Django 4.2.19 on 2025-02-21 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_chatmessage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_pdf_uploader',
            field=models.BooleanField(default=False),
        ),
    ]
